### ISSUE TITLE
List extra files that were attempted to be added as media attachments

### ISSUE THREAD

**Issue by lognaturel** [getodk/central-frontend#138]
As a form designer or campaign manager, if I try to add extraneous files as media attachments, I would like to know what those are so I can remove them from my source files.

To reproduce:
* Add a form that requires media attachments such as [Birds.xml.txt](https://github.com/opendatakit/central-frontend/files/2354090/Birds.xml.txt)
* Go to the Media Files tab
* Drag on one or more files with filenames not included in the form

Current behavior:
<img width="327" alt="screen shot 2018-09-06 at 10 04 26 am" src="https://user-images.githubusercontent.com/967540/45173213-51d9db00-b1bc-11e8-806a-e49791854895.png">

This could be, for example, an expandable section that lists the extraneous files.

**Comment by matthew-white** [comment]
I think it'll be useful to have this functionality! Perhaps one thing to note is that the unmatched files box (the box in the screenshot above with the text "1 file has a name we don't recognize...") is now displayed within the popup, not above it. That means that part of this issue will probably be figuring out the right place to display the list of extraneous files.

**Comment by lognaturel** [comment]
Whoops! I've updated the screenshot, sorry about that. I think that as an admin, you should be able to edit my issues, @matthew-white and do feel free to as you think of more useful info to add or corrections to make.

Agreed that a UI sketch would be a good first step.

**Comment by matthew-white** [comment]
Closing this issue after discussion with @lognaturel.
