### ISSUE TITLE
Make it easier to get the link from Central to Collect

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-frontend#195]
Source https://forum.opendatakit.org/t/odk-central-v0-3-beta/16053/14

> Can you make it easier to get the link from Central into older versions of ODK collect? -- e.g. an option for the url in text form instead of QR code, so that it could be emailed to the device & then cut-n-pasted into the relevant box?

**Comment by matthew-white** [comment]
We're currently discussing stories related to QR code distribution as we plan block 13. We briefly discussed this issue. @lognaturel wrote:

> I don’t think the old versions of Collect reason is very compelling. I think it is annoying to have to go through complicated steps to generate a QR code with settings and that’s where access to the URL could help. Doesn’t feel very high impact to me.

For generating a QR code with settings, hopefully we'll provide a nice answer to that outright at some point.

I think I'll go ahead and close this issue for now. We could also add this idea to our new parking lot document if we want to continue thinking about it.

**Comment by lognaturel** [comment]
I agree with closing this. The other context I'm now remembering I have used the raw URL for is in an emulator. Definitely niche.

There are devices without cameras or broken cameras but they can ingest the QR code image.

**Comment by lognaturel** [comment]
This also comes up in the context of individual data collectors who are geographically disperse needing to configure their devices. My intuition is that it's easier to have them [ingest a QR code image](https://docs.getodk.org/collect-import-export/#importing-settings-from-an-image-saved-on-your-device) than to deal with the raw URL. That URL is hard to copy, wraps weirdly, etc. Copying and pasting is a very different experience based on Android experience so it's hard to describe to low-tech users.

That case is where a username and password would really help. The username should NOT be an email address.
