### ISSUE TITLE
Show full date in title attribute

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#244]
We format dates that we show in Frontend. @issa-tseng writes:

> within a week it shows the day name, and beyond that it shows the exact date. we should make it so that when you hover over a date you always get the exact full date/time though.

I'm thinking we could create a date component that does this.

**Comment by lognaturel** [comment]
I think that behavior would be really great. I use that all the time in Github and it's exactly what I want. Is the discussion more about whether to build a component or about the behavior?

**Comment by matthew-white** [comment]
I think the only question I have is how to format the date in the title attribute. Should it just be how we format dates from a week or more ago? For example, you hover over a date that says `Today 10:00` and see `2019/08/08 10:00`.

**Comment by issa-tseng** [comment]
yup, exactly. let's give them the seconds, too.

**Comment by matthew-white** [comment]
We've now implemented this component in #286. To close out this issue, I think we just need to go through existing components and use this new component wherever we show a date/time.
