### ISSUE TITLE
bump draft box down rather than ellipsify form title

### ISSUE THREAD

**Issue by issa-tseng** [getodk/central-frontend#322]
i sort of feel like we should always be able to see the entire form title. should be able to use floats to do this. not urgent.

**Comment by matthew-white** [comment]
I initially thought I understood what this change would entail, but now I feel less sure. This is what a long form title looks like today:

If there is a form draft:

<img width="1024" alt="Screen Shot 2020-08-24 at 4 58 43 PM" src="https://user-images.githubusercontent.com/5970131/91096241-b30a4b80-e62b-11ea-8553-49963975c711.png">

If there isn't a form draft:

<img width="1024" alt="Screen Shot 2020-08-24 at 4 59 05 PM" src="https://user-images.githubusercontent.com/5970131/91096264-ba315980-e62b-11ea-9fb6-5b6dd7c27fd6.png">

What would be different after this change? The draft tabs are in line with the other form tabs, so would moving the draft box down entail moving down both sets of tabs? I've also implemented this using Bootstrap grid classes, so I'm not totally sure I'll be able to use floats here as it's set up today.

**Comment by issa-tseng** [comment]
yeah, i think that would be the idea. if the title text is too long the whole production moves down to give it some extra room. i'll try to think of alternatives though.

**Comment by matthew-white** [comment]
With the changes coming in v2024.2, this issue should no longer come up. I'll go ahead and close.
