### ISSUE TITLE
Use window.location.href instead of window.location.origin?

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#331]
We use `window.location.origin` in a few places in Frontend. For example, we prefix the app user authentication URL with `window.location.origin`. However, I think that won't work if Frontend is deployed somewhere other than at the site root, because then (for example) the app user authentication URL won't include the URL path after the domain name. I'm thinking that instead of `window.location.origin`, we should use `window.location.href` (after removing the query string and hash). Because we use [hash-based routing](https://router.vuejs.org/guide/essentials/history-mode.html), `window.location.href` should stay constant (except for the hash) as the user navigates within Frontend.

**Comment by matthew-white** [comment]
I'm thinking it might be the case that Backend also assumes that Central is deployed at the site root. For example, we set `Path=/` for the cookie. @issa-tseng, am I right that Backend also makes that assumption? If so, maybe we should document that somewhere, and I'll go ahead and close this issue.

**Comment by matthew-white** [comment]
I'm realizing that Frontend assumes in other places that Central is deployed at the site root. For example, API URLs start with `/v1`. I'm guessing that Backend and/or `central` also assumes that Central is deployed at the site root. I don't think that assumption has been an issue, so I think I'll go ahead and close this issue for now. Interested in whether @lognaturel thinks we should document this assumption anywhere (whether user docs or the `central` readme).

**Comment by issa-tseng** [comment]
yeah i don’t think it’s an uncommon presumption. if we add a feature for relative pathing someday that would touch everyone and tbh i don’t see why we’d do that when you can just proxy rewrite the thing which would be required anyway.

**Comment by Abhinaba12** [comment]
Hey! You are right, we should use "window.location.href" instead of "windows.location.origin".
