### ISSUE TITLE
Update page title after navigation

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#333]
Right now we display "ODK Central" as the page title. I think it'd be nice to update the title as the user navigates within Frontend. I think the main benefit of this would be improved history. We push a new entry into the history stack with each navigation, which allows the user to use the browser back button. However, without updating the title, it's hard to differentiate entries:

<img width="162" alt="Screen Shot 2020-07-01 at 4 33 34 PM" src="https://user-images.githubusercontent.com/5970131/86358840-2bf9b200-bc3e-11ea-8ca8-125be46a2af2.png">

One approach would be to define a route meta field for the title, then register a navigation guard that sets the document title to the value of the meta field after the navigation is confirmed.

However, this wouldn't be enough to show something like the project name in the title, because the response for the project will be received after the navigation is confirmed and the page is initially rendered. For pages like that, a watcher on the data might be the best place to set the title.

@lognaturel, @issa-tseng, do you think updating the page title would be useful? Do you think the title should include things like the project/form/user name?

**Comment by lognaturel** [comment]
Huh, I would have expected to notice this while using Central but I hadn't. Thinking about it, I think it's because there are usually direct ways to get to what I need so I don't use the browser stack much for Central though I do on other sites. This suggests it's probably not very high priority.

I do think it'd be nice to address, though. I'm not exactly sure what should go first. Something static like "project summary", "test submissions", etc might be most helpful because users are likely to be in the context of one project at a time. So I'm thinking something like "Project Roles - My Cool Project - ODK Central", "Submissions - My Cool Form - My Cool Project - ODK Central". Maybe the static part is enough and that would be simpler.

**Comment by matthew-white** [comment]
I feel like something like "Project Roles - My Cool Project - ODK Central" would be ideal, but if we expect that users will usually be in the context of a single project/form/etc. at a time, maybe just "Project Roles - ODK Central" would be enough to differentiate the most recent history entries. Showing a static title per page would definitely be much simpler in terms of code complexity: that way, the implementation wouldn't have to interact with the Vuex store or account for changing data.

Also, I'm thinking that this could be a good issue to label as "help wanted".

**Comment by lognaturel** [comment]
It can also be staged. I think a contributor could very well use the localized page title to get something like "Project Roles - ODK Central" and that would be hugely helpful already. Then possibly in the future the project/form name could be added.

**Comment by matthew-white** [comment]
Do you know offhand whether the "-" between "Project Roles" and "ODK Central" needs to be localized? Based on a quick look, Wikipedia seems to use a hyphen, an en dash, or an em dash depending on the language, but I'm not sure how important that difference is.

**Comment by aaj013** [comment]
> Do you know offhand whether the "-" between "Project Roles" and "ODK Central" needs to be localized? Based on a quick look, Wikipedia seems to use a hyphen, an en dash, or an em dash depending on the language, but I'm not sure how important that difference is.

Another practice which I have seen is using the vertical bar "|" like a separator.

**Comment by matthew-white** [comment]
Thanks, @aaj013! Is there an example site that uses "|" that comes to mind? For sites that use "|", have you noticed whether "|" is used for all languages?

**Comment by aaj013** [comment]
> Thanks, @aaj013! Is there an example site that uses "|" that comes to mind? For sites that use "|", have you noticed whether "|" is used for all languages?

I'm not sure about the use in different languages. But mostly WordPress websites SEO by default using vertical bars as seperators. One example would be the WordPress site itself (https://wordpress.org/download/)

For ref, some discussions regarding the same: https://moz.com/community/q/title-tag-use-comma-pipe-or-colon

**Comment by matthew-white** [comment]
Just now coming back to this, I'm seeing that, for example, Microsoft uses a pipe for all languages: https://powerbi.microsoft.com/en-us/. I think we should start with the pipe, and if we learn that that doesn't work for a particular language, we can always change it.

One other thing to keep in mind is that the title will need to change if the locale changes. For example, if a user is viewing the Project Roles page in English, the title should read "Project Roles | ODK Central". If the user then changes the locale to Spanish, the title should read "Roles del proyecto | ODK Central".
