### ISSUE TITLE
Account for long user display name in navbar

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#348]
Right now if a user's display name is too long, the dropdowns in the navbar appear below the navbar:

<img width="808" alt="Screen Shot 2020-07-19 at 8 55 49 AM" src="https://user-images.githubusercontent.com/5970131/88196401-25dc6d00-cc0f-11ea-8c3a-da92ffe2f6cc.png">

Instead, we should truncate the name if it is greater than a certain width, specifying `text-overflow: ellipsis`. We should add a tooltip like we do elsewhere so that the full name can still be seen.

We do something similar in the `FormVersionSummaryItem` component:

<img width="481" alt="Screen Shot 2020-07-22 at 11 29 22 AM" src="https://user-images.githubusercontent.com/5970131/88196654-7358da00-cc0f-11ea-8a72-0ef70438bcff.png">

**Comment by matthew-white** [comment]
@getodk/testers, this fix can be verified at any time on staging.

**Comment by dbemke** [comment]
**Tested with success!**
