### ISSUE TITLE
Add navbar links to get help

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#350]
@lognaturel, @issa-tseng, what do you think about adding link(s) to the navbar dropdown that link to the docs and/or the forum? One possibility is that these links could go between "Edit profile" and "Log out".

Also CC @florianm, who made a related [comment](https://forum.getodk.org/t/odk-central-is-ready-for-translating/28491/7) on the forum.

**Comment by florianm** [comment]
Links to server diagnostics or docs/forum would be great! 

e.g. 
- a hint to open the browser console might save a round trip to the forum
- an expanding section in error messages to "view details" which I can copy straight away would save a round trip to the browser console and could include details about central version, deployment, issue with certificates etc (similar to R sessionInfo())
- if error is known / occurs often due to incorrect config / relevant to server maintainers: a link to the FAQ or a preformed link to search the forum for that error.

**Comment by matthew-white** [comment]
Thanks, @florianm! Some of these ideas wouldn't be easy to implement today, but I like the idea of improving the user experience around errors. I'm going to throw out a couple of thoughts related to how Frontend handles errors today, then I'll show a screenshot of what I'm currently thinking.

Currently Frontend doesn't have information about the deployment, including the version of Central. Frontend could fetch /version.txt, and we could try to set up ops to provide Frontend other information about the deployment, but that's not something we have set up today. (Also linking to the related https://github.com/getodk/central/issues/59.)

There's a way in Frontend to read the details from a Backend error and display them in a human-readable way. The aim is for the Frontend error message to contain all the information that the user needs. For example, we [use that mechanism](https://github.com/getodk/central-frontend/blob/4732f7112a286165241aaf7f971f2c2e38d6bb8a/src/components/form/new.vue#L285-L287) in the modal that's used to create a form or upload a new form definition. However, I think there are probably more places we could use that mechanism: https://github.com/getodk/central/issues/144 may be an example of this.

Here are a couple of screenshots of what I think might be a quick win. I've updated the navbar to link to the docs, the forum, and /version.txt. We already link to the docs and the forum from the Central homepage, but this change would make those links accessible in more places.

Version 1: Add the links to the existing dropdown:

<img width="171" alt="Screen Shot 2020-08-23 at 12 05 31 PM" src="https://user-images.githubusercontent.com/5970131/90983522-d5716b80-e53c-11ea-93af-00ff47fde55d.png">

Version 2: Add a new help menu:

<img width="171" alt="Screen Shot 2020-08-23 at 1 02 32 PM" src="https://user-images.githubusercontent.com/5970131/90984122-11a6cb00-e541-11ea-8f7f-3cf0575bf1b7.png">

**Comment by florianm** [comment]
As an ODK Central user who just experienced an error, my first thoughts are "what's wrong exactly" and "where can I find a solution". The question mark icon in Version 2 is the most logical symbology for me to open, more than my profile/name.

Shower thought: "log" + "audit" + "console" = Win 10-like notification stream? Let this area display errors (with a link to the forum that contains a few targeted keywords) and make it unobtrusive yet discoverable.

**Comment by issa-tseng** [comment]
the latter feels closer to me but I don't like the order and placement.

can we mirror the left side a little and do something like

[? v] [lang v] [space] [name v]
