### ISSUE TITLE
Standard form buttons wrap in French

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#370]
The "standard form buttons" include the Preview button and the Download button. In English, they are shown on a single line. However, in French (and possibly other locales), they can wrap onto a second line, because the text of the buttons is longer.

On the form overview page:

<img width="1178" alt="overview_fr" src="https://user-images.githubusercontent.com/5970131/91074082-11becd80-e60a-11ea-8f58-1abbeeeefcaa.png">

On the draft status page:

<img width="583" alt="status_fr" src="https://user-images.githubusercontent.com/5970131/91074096-15525480-e60a-11ea-9c51-52257d7f6e20.png">

Given the length of the button text, it might be hard to keep the buttons on a single line along with the version string. I think it might work best to move the buttons below the version string. For example:

On the form overview page:

<img width="340" alt="Screen Shot 2020-08-20 at 5 59 29 AM" src="https://user-images.githubusercontent.com/5970131/91074559-be994a80-e60a-11ea-8f0a-7e62f66fe285.png">

On the draft status page:

<img width="353" alt="Screen Shot 2020-08-20 at 5 57 40 AM" src="https://user-images.githubusercontent.com/5970131/91074538-b8a36980-e60a-11ea-8f01-efc7329f5837.png">

On the draft status page, we could also consider moving the "Upload new definition" button down to the Actions section, joining the "Publish Draft" and "Abandon Draft" buttons.

**Comment by issa-tseng** [comment]
the screenshots seem fine to me for now
