### ISSUE TITLE
Show warning if user selects 100+ columns

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#396]
Above the submissions table, we show a dropdown that allows the user to select the columns to display in the table. We only allow the user to select 100 columns at a time, because anything above that takes some time to render. For example, on my computer it takes about 3 seconds to render 100 columns for 250 submissions.

However, instead of disabling additional selection after 100 columns, it would be better to simply warn the user about the potential slowdown. That way, the user can select additional columns if they want to while knowing what to expect. Removing the logic in the `SubmissionFieldDropdown` component around disabling should also simplify that component.

If the user selects 100+ columns, they should see a warning beneath the list of fields. The warning should show an `.icon-exclamation-triangle` as we do elsewhere, alongside the text "Selecting too many columns might slow down your computer."

**Comment by elmarek** [comment]
Hi Matthew, I'm going to give this issue a go.  Hopefully submit a pull request soon.  Thanks!

**Comment by matthew-white** [comment]
Thanks, @elmarek! 🚀
