### ISSUE TITLE
Include filter selections in URLs

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#525]
Moved from the block 14 release criteria:

> - If I am viewing the Submissions table or the Server Audit Log, and I make one or more filter selections
>   - then my filter selections should appear in the URL
>   - and if I load that URL in a different tab, I should see the same filter selections applied

I took a first look at this, and mostly it seemed quite doable. We will very likely want to reuse components after the URL changes, but I don't think any changes will be needed to `asyncRoute()` or `createRoutes()`. Often when a component is reused after a route change, it needs to watch `$route`, but I'm not sure that `SubmissionList` will need to do even that.

So far, the one part that does seem more complicated is what to do if the URL includes an invalid filter selection. That could happen if the user copies and pastes a URL incorrectly. Once we support purging submissions, it could also happen if all the submissions for a particular submitter are purged (such that the submitter is no longer one of the filter's options). It seems potentially fine for invalid filter selections to be included in the Backend request, but I want to make sure that Frontend components won't break (specifically those in `SubmissionFilters`).

Another thing I have been wondering about is whether to include the list of selected fields in the URL. I wasn't planning to for block 14, but I could see that being useful behavior in some cases. On the other hand, the list of selected fields could be quite long. On the other other hand, maybe we could gzip and encode it or something?

**Comment by matthew-white** [comment]
This was done for the submissions table in #587. We still want to do this for the server audit log.

**Comment by matthew-white** [comment]
> Another thing I have been wondering about is whether to include the list of selected fields in the URL.

I'm currently working on this issue, but I'm not going to address this part about selected fields. I could file a new issue about that if we decide that it'd be useful.

**Comment by matthew-white** [comment]
@getodk/testers, this issue is ready to be verified on the staging server. The change for v2023.5 has to do with the Server Audit Logs page:

- If you change either or both filters on the page, then the new filter selection should appear in the URL.
  - But if you select the default for a filter ("All Actions" or today's date), then the selection for that filter won't appear in the URL.
- If you copy the URL and open it in a new tab, you should see that the filter selections in the URL are immediately applied.

**Comment by srujner** [comment]
@matthew-white 
Hey, is this ok that there is no validation in URL? I can provide there any special cases and then the filter becomes default 
(It shows All Actions) 
![central](https://github.com/getodk/central-frontend/assets/85225519/6e52d6a3-c17c-449a-a630-2ebaba3612e6)

Second case, when I write '#' after the filter, then all the special characters etc. are ignored. 
We just want to make sure that this is correct behavior, all other things are working fine
![central2](https://github.com/getodk/central-frontend/assets/85225519/07d886d2-b1db-4c5a-bb0c-8448a6c74653)

**Comment by matthew-white** [comment]
Good questions!

> is this ok that there is no validation in URL? I can provide there any special cases and then the filter becomes default

That's expected. If a value is specified in the URL that isn't in the list, then it falls back to the default (All Actions). The submission filters work in a similar way. For example, if you specify `?reviewState=blue` on the submissions page, then it falls back to all review states.

> Second case, when I write '#' after the filter, then all the special characters etc. are ignored.

That's also expected. In that case, the `#` is interpreted as the start of a different part of the URL, the fragment identifier. (And the fragment identifier doesn't have an effect on that page, so it's basically ignored.)

> If a manually change the filtered date (in the URL) to a wrong date e.g. start 2024 year and finish 2023 then the current date is shown.

Similar to an invalid action, if the date range is invalid for any reason, then it should fall back to the default (the current date). That includes the case where the start date is after the end date.

> After that, If I change the Type filter, the URL with the wrong date is still in the URL (different date shown in the filter) + added the Type filter. Should the URL get corrected after adding a filter (by using the filter field) to some wrong URL?

Each filter is synced with particular query parameters, so changing one filter won't affect the query parameter(s) used by another filter. That means that changing the Type filter will only have an effect on the `action` query parameter. If you specify an invalid value for another filter, then it will stay in the URL until that filter is changed. I could see how it'd be nice to correct invalid values in the URL (maybe even immediately). However, invalid values in the URL shouldn't be a problem, since they should fall back to the default. I think they'll be pretty uncommon (like copying a URL incorrectly before pasting it in).

**Comment by dbemke** [comment]
**Tested with Success!**
