### ISSUE TITLE
Update background color of form access table

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#557]
Right now it can be hard to distinguish the rows of the form access table. It would be helpful to vary the background color.

Ideally, when the user hovers over a row of the table, a background color should be set for the row. This is harder than it sounds because of how the frozen columns are set up. However, we could do something similar to what we do for the submissions table.

An alternative that I think would be easier would be to set a gray background color for the middle of every three rows (3n + 1?). A complication here is that form drafts already have a background color. Because of that, we should sort form drafts to the bottom of the table. Above the drafts should be the text "Drafts" (or something similar). This text could even go in its own table row if that's easiest.

If we redo form access as part of v1.6, then we can just close this issue.

**Comment by matthew-white** [comment]
@lognaturel, it seems like we're waiting until we harmonize the user model to work on this, right? Do you mind if I close this issue?

**Comment by lognaturel** [comment]
I think so. Hopefully that screen goes away sooner than later.
