### ISSUE TITLE
Instant tooltips

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#648]
Moved from the v2022.3 release criteria:

- On anything with title text, show our own popup with the text right away, rather than make people wait for the browser.
  - GitHub has done this forever, for example. It’s a big big usability win.
- Focusing on a title-text element with keyboard navigation should ideally also pop the tip.
- (Nice to have:) Today there are elements where if their text content overflows, we truncate the text with an ellipsis; we also add title text. The title text is added even if the text content does not actually end up overflowing: the title text is added if the text content might overflow. However, ideally we show an instant tooltip only if the text content actually overflows.

**Comment by srujner** [comment]
**Tested wit Success!**

**Comment by dbemke** [comment]
**Tested with Success!**

**Comment by matthew-white** [comment]
I've filed an issue with design review feedback at #753. We didn't end up making those changes for .2, but we're planning to do so for .3.
