### ISSUE TITLE
Check dataset/entity verbs in more places

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#662]
Most routes require that the current user be able to do certain verbs (either sitewide or on a particular project). If the user tries to navigate to a route that requires a verb that they can't do, then they are redirected to the homepage. I think it's a good idea for the route to check every verb that the route component might require, unless the component itself checks the verb as part of rendering something conditionally (for example, using `LinkIfCan`). With that in mind, I think we should check dataset and entity verbs for more routes:

- `FormOverview` and `FormDraftStatus` should check `dataset.list` because they request &hellip;/dataset-diff.
- `FormAttachmentList` should check `entity.list` because it allows the user to link a form attachment to a dataset.
- Maybe others?

Given that this doesn't come up for our current roles and we don't have custom roles, and we rely on the API to do these checks anyway, I don't think this is something we need to do for v2022.3. However, I think it'd be a good idea to add this at some point.

**Comment by ktuite** [comment]
Note for the future, backend probably needs a `dataset.read` verb.

**Comment by matthew-white** [comment]
getodk/central-backend#808 adds that `dataset.read` verb to Backend. As part of this issue, we should use `dataset.read` wherever that verb would be appropriate, possibly replacing some current uses of `dataset.list`.
