### ISSUE TITLE
Render links for XLSForm warning URLs

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#687]
A few XLSForm warnings end with "Learn more: [some URL]". Currently, we don't linkify that URL: it is rendered as text. However, it would be helpful if we rendered a link instead.

**Comment by lognaturel** [comment]
Well that's cool! I see from https://github.com/getodk/central-frontend/pull/685/files#diff-297d623ca753d07d496717ce4e92f55d4a3f4a6398a40b2be246c3b53e858bdcR257 that this is specifically looking for a "Learn more:" prefix which is not necessarily consistently used in `pyxform`. We should probably make this a documented pattern if we're going to rely on it, right?

**Comment by sadiqkhoja** [comment]
I want to make all links consistent in warning box:

![image](https://user-images.githubusercontent.com/447837/211109963-ab11fc9b-fee7-453f-bbe8-bc66702c1439.png)


I searched for `xlsform.org` in pyxform repository (https://github.com/XLSForm/pyxform/search?q=xlsform.org) and found that all the help links have "Learn more" prefix, is there any other patter?

**Comment by lognaturel** [comment]
> is there any other patter

No. But this one is not documented. https://github.com/XLSForm/pyxform/issues/634

**Comment by srujner** [comment]
Tested with Success!

**Comment by dbemke** [comment]
Tested with Success!
