### ISSUE TITLE
"Latest Submission" tooltip not shown over date/time

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#698]
When you hover over a cell of a forms table (on the homepage or in the project overview), then a tooltip will appear over most cells describing what the column shows. One of the columns is the date/time of the latest submission. If you hover over that column, you're supposed to see the text "Latest Submission". However, date/times have their own tooltips to show the date/time in a more precise format that is always absolute, not relative. That means that if you hover over a date/time, you won't see the "Latest Submission" tooltip, only the date/time tooltip. It's only if you hover over the clock icon or the text "(none)" (if there are no submissions) that you see the "Latest Submission" tooltip.

To address this, we will combine these two tooltips. If a date/time is shown, then when you hover over the cell, you will see a single tooltip that includes both the text "Latest Submission" and the absolute date/time.

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
**Tested with Success!**
