### ISSUE TITLE
Add pyODK to OData modal

### ISSUE THREAD

**Issue by yanokwa** [getodk/central-frontend#740]
1. Change the initial paragraph to the text below. Note that Power BI is first, and we've added a link for Excel.
> OData is a standard for transferring data between tools and services. Powerful analysis tools like Power BI (https://powerbi.microsoft.com/en-us/), Excel (https://www.microsoft.com/en-us/microsoft-365/excel), Python (https://www.python.org/), and R (https://www.r-project.org/) can fetch data via OData for analysis.
> 
> To connect to this form's OData feed, select your tool and copy the link into it.

2. Add a Python pane before R panel with the following blurb.
> To connect to Central from Python, we recommend pyODK (https://github.com/getodk/pyodk/). pyODK is the official Python client for Central and it makes common data analysis and workflow automation tasks simple.

3. Simplify R blurb
> To connect to Central from R, we recommend ruODK (https://docs.ropensci.org/ruODK/). ruODK is developed and supported by ODK community members.

4. Change "Excel/Power BI" to "Power BI or Excel" on the header. Looks better to me, and I think Power BI should be first.

5. Update Excel link in blurb.
> For help using OData with Power BI, see this page (https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-odata). For help with Excel, see this page (https://support.microsoft.com/en-us/office/about-power-query-in-excel-7104fbee-9e62-4cb9-a02e-5bfb1a6c536a).

**Comment by lognaturel** [comment]
While here, can we do "new standard" -> "standard"? As much as it pains me to admit it, 2015 was a while ago now (OASIS standardization).

**Comment by yanokwa** [comment]
Based on https://forum.getodk.org/t/analyze-via-odata-does-not-seem-to-work/40536, it seems like this dialog might have too much text. I've removed the second paragraph on the pop up.
