### ISSUE TITLE
Add infinite scroll to Entities table

### ISSUE THREAD

**Issue by ktuite** [getodk/central-frontend#741]
For v2023.2, we are just loading the entire block of entities to show in the entity table. For the following release, when we likely add bulk CSV managing of entities, we will want to add the same kind of chunking and infinite scroll that we have for submissions. 

We will likely want to reuse functionality from the submission chunking/scrolling and make a generic infinite scroll odata table. 

Note about infinite scroll vs. paging: one use case we see in practice is loading a bunch of submissions and then searching on the page itself for specific content. This is a pretty good case for sticking with infinite scroll until we have the ability to search submission/entity content.

**Comment by matthew-white** [comment]
Alongside this, I think we should use the `useChunkyArray()` composable with the entities table, as we do with the submissions table.

**Comment by matthew-white** [comment]
This issue is currently blocked by getodk/central-backend#665.

**Comment by matthew-white** [comment]
> I think we should use the `useChunkyArray()` composable with the entities table

That could happen as part of #851, but I also think it'd be fine for it to happen separately (even in .5).

**Comment by dbemke** [comment]
Is it ready for testing?

**Comment by sadiqkhoja** [comment]
yes

**Comment by matthew-white** [comment]
@sadiqkhoja, is there anything you think the QA team should look at specifically while verifying this change? Maybe cases related to concurrent modification? (Just a thought.)

I'm wondering whether it'd be helpful for you to create an entity list on staging with 1,000 or 2,000 entities — something that the QA team could use to verify this change. Alternatively, I think the QA team knows how to create an entity using the API and Postman. If you could show them a way in Postman or another tool to send many requests (in a loop?), then they could create their own large entity list. (One day we'll have bulk upload, and this will be easier!)

**Comment by sadiqkhoja** [comment]
I will meet with QA team to show them how to use Postman for bulk operations

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by matthew-white** [comment]
@sadiqkhoja, @dbemke left a comment [here](https://github.com/getodk/central/issues/385#issuecomment-1723105553) that I'm thinking may be related to the changes here.
