### ISSUE TITLE
Linkify project name in DatasetShow

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#748]
Dataset pages show the project name at the top:

My Project > Datasets

This is similar to form pages, which likewise show the project name at the top:

My Project > Forms

On form pages, the project name links to the project overview. However, the project name does not link on dataset pages. I think it's intuitive to try clicking the project name (and have tried to do so myself), so I think we should linkify it.

Question: Should the project name link to the dataset list or to the project overview? (If the former, we can just use the existing `linkTitle` prop of the `PageBack` component. If the latter, then we should probably modify `PageBack`.) My instinct is that it should link to the project overview.

**Comment by lognaturel** [comment]
Agreed it should be the project overview. I think we should try to do this before release.
