### ISSUE TITLE
problem 405 (Method Not Allowed) after making a build, running dev disconnects on refresh, no generating form link

### ISSUE THREAD

**Issue by Ono-T1m** [getodk/central-frontend#786]
deployed the backend successfully with pm2, on ubuntu server
when i deploy the front (npm run build) with nginx i can access the login page but cannot connect
in console i get 405 (Method Not Allowed)
using the testing (npm run dev) works and can login
this is running on a virtual machine without domain just static ip ubuntu 20 postgresql 14 node 16 without docker
now the dev version can be run with npm permanently but everytime i refresh the webpage it logs out, and the link to share an uploaded form doesn't generate.
any help please?

**Comment by matthew-white** [comment]
Hi @Ono-T1m! I can't tell whether you're trying to set up Central Frontend for local development. If you're deploying Central to a server, you should check out our [Docker infrastructure](https://github.com/getodk/central). That's the only infrastructure for deploying Central that we support. Note that the nginx config in this repository is intended for local development only. `npm run dev` is also intended for local development only.

In the future and for any follow-up questions, please post to the ODK forum. More of the community is on the forum and will be able to see your questions there.

**Comment by Ono-T1m** [comment]
> Hi @Ono-T1m! I can't tell whether you're trying to set up Central Frontend for local development. If you're deploying Central to a server, you should check out our [Docker infrastructure](https://github.com/getodk/central). That's the only infrastructure for deploying Central that we support. Note that the nginx config in this repository is intended for local development only. `npm run dev` is also intended for local development only.
> 
> In the future and for any follow-up questions, please post to the ODK forum. More of the community is on the forum and will be able to see your questions there.

This is for a local test only without docker, thanks for mentioning the forum
