### ISSUE TITLE
Frontend reports “Incorrect email address and/or password” over and over when credentials are correct

### ISSUE THREAD

**Issue by lognaturel** [getodk/central-frontend#825]
I’ve occasionally gotten stuck in a state where frontend reports “Incorrect email address and/or password” even though I know my credentials are correct.

This happens to me most on mobile (Chrome in iOS) but it has happened from my laptop too.

At first I thought it might be related to my password manager but it happened to me as I was trying to type a password from memory. 

I have not figured out a reliable way to get out of this state. I usually refresh many times, try incognito, and eventually it seems to let me through. 

I tried to reproduce earlier this week and I could not. @matthew-white has mentioned he thinks it could be related to connectivity issues. Yesterday I was on a poor mobile connection, tried to log in to test.getodk.cloud, and got the error. I’m now back on my fast and reliable connection but still can’t log in so there is something persistent about this state. 

When I was trying to reproduce, I used several different accounts. This could be something unusual about my usage: I do frequently switch between accounts.

**Comment by matthew-white** [comment]
We're having some trouble reproducing. I'm going to go ahead and close for now, but we can reopen if/when we get more information or want to explore further.

**Comment by lognaturel** [comment]
With Chrome on iOS, I can consistently get into a similar state by doing the following: logging in as one user, turning off Wi-Fi, logging out, turning on Wi-Fi, attempting to log in as another user. I have just verified this again now.

I can't reproduce with those steps on Firefox on macOS.

Seems right to close for now. It must be a combination of mobile (maybe just Chrome) + multiple users + session timeouts.
