### ISSUE TITLE
Remove polling for Enketo IDs

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#865]
The most complicated part of the `FormShow` component is polling Backend for Enketo IDs for a form or form draft that's missing them. With getodk/central#385 in place, it should be the case that Backend returns Enketo IDs immediately in the vast majority of cases, making that polling much less useful. If that proves to be true in experience, I think we should strongly consider removing that polling from Frontend as a source of complexity that's outlived its usefulness. That polling is also noisy during local development if you don't have Enketo set up.

`EnketoPreview` and `EnketoFill` already recommend refreshing, so I don't think any text would need to change:

https://github.com/getodk/central-frontend/blob/972062f259293877ca2f718aefc83ad80979f2ca/src/components/enketo/preview.vue#L57
https://github.com/getodk/central-frontend/blob/972062f259293877ca2f718aefc83ad80979f2ca/src/components/enketo/fill.vue#L55

**Comment by matthew-white** [comment]
> If that proves to be true in experience

@lognaturel, how have things been going in terms of Backend being able to fetch Enketo IDs synchronously instead of async? If it's now rare that Enketo IDs are fetched async, I'd love to remove this polling from Frontend.

**Comment by lognaturel** [comment]
Can you please remind me what action I was supposed to take? 🫣 It's my believe that Enketo's response has always been immediate and synchronous. Maybe I should verify in the Enketo source?

**Comment by matthew-white** [comment]
Mostly I'm curious about what you've seen in practice. When you create a form or create a form draft or replace an existing form draft or publish a form draft, are the buttons in Frontend that link to Enketo enabled right away? I guess if Enketo's response is immediate, that should mean that the buttons in Frontend are enabled right away. I don't think you necessarily need to verify that in the source; mostly I'm interested in your observations in practice. (Assuming that enough time has passed since v2023.4 to make that determination.) I'm eager to remove the polling described above from Frontend, but first I want to confirm that it is useful only rarely if ever.

**Comment by lognaturel** [comment]
I use all of the all the time and have never seen it disabled since the 2023.4 changes! It has greatly, greatly improved my life.
